owner: simon2871 # GitHub username
repo: fs-websitemonitor # GitHub repository name
sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
  - name: ${{secrets.FS_SITE1}}
    url: https://$FS_SITE1/
assignees: simon2871 # Users to assign downtime issues (optional)
#status-website: # Status website (optional)
# cname: upptime.js.org # Custom domain CNAME
#name: Upptime # Status website title
status-website:
  baseUrl: /fs-websitemonitor # where "repo" is your repository name
  name: Your Status Website
